services:
  remindarr:
    build: .
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - remindarr_db
    command: uvicorn main:app --host ${API_HOST} --port ${API_PORT} --reload

  remindarr_db:
    image: postgres:16
    container_name: remindarr_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT_EXTERNAL}:${DB_PORT}"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d remindarr"]
      interval: 10s
      retries: 5
      start_period: 15s
      timeout: 5s